### ISSUE TITLE
Windows Settings

### ISSUE THREAD

**Issue by scyrc2** [KokyoK/OpenGL-CG-2021#1]
The method for memory allocation is not safe for windows. Can you update it?

**Comment by KokyoK** [comment]
Hi Bro,
Windows does not a variable-length array, thus I modified ` Loader.cpp`. It is now in branch _windows_.
 Two ways can be used: vectors and double-pointer. Vectors will significantly reduce the running efficiency, so I uploaded the double-pointer version.
